<?php

// Load Nette Framework or autoloader generated by Composer
require LIBS_DIR . 'autoload.php';

$configurator = new Nette\Config\Configurator;

// Enable Nette Debugger for error visualisation & logging
//$configurator->setDebugMode(TRUE);
$configurator->enableDebugger(__DIR__ . '/../log');

// Enable RobotLoader - this will load all classes automatically
$configurator->setTempDirectory(__DIR__ . '/../temp');
$configurator->createRobotLoader()
	->addDirectory(APP_DIR)
	->addDirectory(LIBS_DIR)
	->register();

// Create Dependency Injection container from config.neon file
$configurator->addConfig(__DIR__ . '/config/config.neon');
$configurator->addConfig(__DIR__ . '/config/config.local.neon', $configurator::NONE); // none section

// Setup 'dibi' extension for config.neon
$configurator->onCompile[] = function($configurator, $compiler) {
	$compiler->addExtension('dibi', new DibiNetteExtension);
};

$container = $configurator->createContainer();


return $container;
